[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "image-processor"
version = "0.1.0"
description = "Flask image processing application"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
